*DEFINE_CURVE_DRAWBEAD_TITLE
$#                                                                         title
                                                                                
$#     cid     tcype       vid       pid     blkid     perct
         1         1         0         0         0         0
$#                cx                  cy
                                        
                                        
