*DEFINE_CURVE_TRIM_TITLE
$#                                                                         title
                                                                                
$#    tcid    tctype         -         -     tctol
         1         1                          0.25
$#                cx                  cy
                                        
                                        
