*DEFINE_CURVE_5434A_TITLE
$#                                                                         title
                                                                                
$#    lcid      sidr       sfa       sfo      offa      offo    dattyp     lcint
         1         0         1         1         0         0         0         0
$#                a1                  o1
                                        
                                        