*DEFINE_CURVE_ENTITY_TITLE
$#                                                                         title
                                                                                
$#    lcid       sfa       sfo       sfr      offa      offo      offr
         1         1         1         1         0         0         0
$#                ai                  oi                  ri               iflag
                                                                               0
                                                                               0
