*DEFINE_CURVE_STRESS_TITLE
$#                                                                         title
                                                                                
$#    lcid     itype        p1        p2        p3        p4        p5        p6
         1         0         0         0         0         0         0         0
*DEFINE_CURVE_STRESS_TITLE
$#                                                                         title
                                                                                
$#    lcid     itype        p1        p2        p3        p4        p5        p6
         1        11         0         0         0         0         0         0
$#    lcid     itype        p1        p2        p3        p4        p5        p6
         0         01.4574E-43-1.231E+30-1.460E-421.9290E-392.1120E-39-1.236E+30
