*DEFINE_CURVE_FUNCTION
$#    lcid      sidr       sfa       sfo      offa      offo    dattyp
         1         0         1         1         0         0         0
$#                                                                      function
                                                                                
                                                                                
