*DEFINE_CURVE_BOX_ADAPTIVITY_TITLE
$#                                                                         title
                                                                                
$#      id       pid     level     dist1
         1         0         0         0
$#                 x                   y                   z
                                                            
                                                            