*DEFINE_CURVE_FUNCTION_TITLE
$#                                                                         title
                                                                                
$#    lcid      sidr       sfa       sfo      offa      offo    dattyp
         1         0         1         1         0         0         0
$#                                                                      function
                                                                                
                                                                                
