*DEFINE_CURVE_COMPENSATION_CONSTRAINT_BEGIN_TITLE
$#                                                                         title
                                                                                
$#   crvid    in/out
         1         0
$#             x               y               z
                                                
                                                
