*CONTROL_OUTPUT
$#   npopt    neecho    nrefup    iaccop     opifs    ipnint    ikedit    iflush
         0         0         0         0         0         0       100      5000
$#   iprtf    ierode   tet10s8    msgmax    ipcurv      gmdt   ip1dblt      eocs
         0         0         2        50         0         0         0         0
$#   tolev    newleg    frfreq     minfo    solsig    msgflg    cdetol     igeom
         2         0         1         0         0         0        10         1
$# phschng    demden   icrfile   spc2bnd    penout    shlsig   hisnout    engout
         0         0         0         0         0         0         0         0
$#    insf    isolsf      ibsf      issf    mlkbag    kineng
         0         0         0         0         0         0
