*TEST_MIXED
$#                                                                                   title
                                            Test of mixed variables without optional cards
$#     kid        v1        v2        v3        v4        v5        v6        v7        v8
         1        -1         1        -11.2346E+10-1.235E+101.2346E-12-1.235E-12random_lon
$#     vv0       vv1       vv2       vv3       vv4       vv5       vv6       vv7       vv8
         1        -1         1        -11.2346E+10-1.235E+101.2346E-12-1.235E-12random_str
         2        -2         2        -22.3457E+10-2.346E+102.3457E-12-2.346E-12random_str