*TEST_MIXED_OPTIONAL
$#                                                                                   title
                                               Test of mixed variables with optional cards
$#     kid     trig2     var23     var24     var25     var26     var27     var28     var29
         1        -1         1        -11.2346E+10-1.235E+101.2346E-12-1.235E-12random_lon
*TEST_MIXED_OPTIONAL
$#                                                                                   title
                                               Test of mixed variables with optional cards
$#     kid     trig2     var23     var24     var25     var26     var27     var28     var29
         1         1         1        -11.2346E+10-1.235E+101.2346E-12-1.235E-12random_lon
$#   var31     trig3     var33     var34     var35     var36     var37     var38     var39
         1        -1         1        -11.2346E+10-1.235E+101.2346E-12-1.235E-12random_lon
*TEST_MIXED_OPTIONAL
$#                                                                                   title
                                               Test of mixed variables with optional cards
$#     kid     trig2     var23     var24     var25     var26     var27     var28     var29
         1         1         1        -11.2346E+10-1.235E+101.2346E-12-1.235E-12random_lon
$#   var31     trig3     var33     var34     var35     var36     var37     var38     var39
         1         1         1        -11.2346E+10-1.235E+101.2346E-12-1.235E-12random_lon
$#   var41     trig4     var43     var44     var45     var46     var47     var48     var49
         1        -1         1        -11.2346E+10-1.235E+101.2346E-12-1.235E-12random_str
         2        -2         2        -22.3457E+10-2.346E+102.3457E-12-2.346E-12random_str
