*TEST_SCALAR_OPTIONAL
$#                                                                                   title
                                              Test of scalar variables with optional cards
$#      id     trig2     var23     var24     var25     var26     var27     var28     var29
         1        -1         1        -11.2346E+10-1.235E+101.2346E-12-1.235E-12random_lon
*TEST_SCALAR_OPTIONAL
$#                                                                                   title
                                              Test of scalar variables with optional cards
$#      id     trig2     var23     var24     var25     var26     var27     var28     var29
         1         1         1        -11.2346E+10-1.235E+101.2346E-12-1.235E-12random_lon
$#   var31     trig3     var33     var34     var35     var36     var37     var38     var39
         1        -1         1        -11.2346E+10-1.235E+101.2346E-12-1.235E-12random_lon
*TEST_SCALAR_OPTIONAL
$#                                                                                   title
                                              Test of scalar variables with optional cards
$#      id     trig2     var23     var24     var25     var26     var27     var28     var29
         1         1         1        -11.2346E+10-1.235E+101.2346E-12-1.235E-12random_lon
$#   var31     trig3     var33     var34     var35     var36     var37     var38     var39
         1         1         1        -11.2346E+10-1.235E+101.2346E-12-1.235E-12random_lon
$#   var41     trig4     var43     var44     var45     var46     var47     var48     var49
         1        -1         1        -11.2346E+10-1.235E+101.2346E-12-1.235E-12random_lon
