*TEST_VECTOR
$#                                                                                   title
                                        Test of vectorial variables without optional cards
$#    svip      svin     svfps     svfns     svfpl     svfnl  svfpsmal  svfnsmal     svstr
         1         1        -1         11.2346E+10-1.235E+101.2346E-12-1.235E-12random_str
         2         2                   22.3457E+10-2.346E+102.3457E-12-2.346E-12random_str
                   3                                                                      
                   4                                                                      