*ELEMENT_BEAM_SECTION_SCALAR
$#   eid     pid      n1      n2      n3     rt1     rr1     rt2     rr2   local
       1       0       0       0       0       0       0       0       0       2
$#   stype        d1        d2        d3        d4
SECTION_01         0         0         0         0
$#           vol            iner             cid           dofn1           dofn2
               0               0               0               1               1
