*ELEMENT_BEAM_SCALAR_ORIENTATION
$#   eid     pid      n1      n2      n3     rt1     rr1     rt2     rr2   local
       1       0       0       0       0       0       0       0       0       2
$#           vol            iner             cid           dofn1           dofn2
               0               0               0               1               1
$#      vx        vy        vz
         0         0         0
