*ELEMENT_BEAM_THICKNESS_SCALAR
$#   eid     pid      n1      n2      n3     rt1     rr1     rt2     rr2   local
       1       0       0       0       0       0       0       0       0       2
$#         parm1           parm2           parm3           parm4           parm5
               0               0               0               0               0
$#           vol            iner             cid           dofn1           dofn2
               0               0               0               1               1
