*ELEMENT_BEAM_THICKNESS_ORIENTATION
$#   eid     pid      n1      n2      n3     rt1     rr1     rt2     rr2   local
       1       0       0       0       0       0       0       0       0       2
$#         parm1           parm2           parm3           parm4           parm5
               0               0               0               0               0
$#      vx        vy        vz
         0         0         0
