*BOUNDARY_PRESCRIBED_MOTION_SET_BOX_ID
$#      id                                                               heading
         1                                                                      
$#  typeid       dof       vad      lcid        sf       vid     death     birth
         0         0         0         0         1         01.0000E+28         0
$#   boxid   toffset    lcbchk
         0         0         0
*BOUNDARY_PRESCRIBED_MOTION_SET_BOX_ID
$#      id                                                               heading
         1                                                                      
$#  typeid       dof       vad      lcid        sf       vid     death     birth
         0         0         4         0         1         01.0000E+28         0
$#   boxid   toffset    lcbchk
         0         0         0
$# offset1   offset2       lrb     node1     node2
         0         0         0         0         0
