*BOUNDARY_PRESCRIBED_MOTION_RIGID_LOCAL_BNDOUT2DYNAIN_ID
$#      id                                                               heading
         1                                                                      
$#     pid       dof       vad      lcid        sf       vid     death     birth
         0         0         0         0         1         01.0000E+28         0
$#    prmr
          
*BOUNDARY_PRESCRIBED_MOTION_RIGID_LOCAL_BNDOUT2DYNAIN_ID
$#      id                                                               heading
         1                                                                      
$#     pid       dof       vad      lcid        sf       vid     death     birth
         0         0         4         0         1         01.0000E+28         0
$# offset1   offset2       lrb     node1     node2
         0         0         0         0         0
$#    prmr
          
